# tmux 기본 shell — bash
set-option -g default-shell "/bin/bash"
set-option -g default-command "/bin/bash"

# 256색 + truecolor
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# 마우스 지원
set -g mouse on

# 히스토리 버퍼
set -g history-limit 10000
